"""Run the complete offline workflow on a deterministic synthetic GB1-like landscape.

This demonstration deliberately does not load the uncommitted GB1 CSV, ESM cache, or
an API key.  Its outputs are labelled synthetic and must never be used as formal results.
"""
from __future__ import annotations

import json
from itertools import product
from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import evolution.campaign as campaign
from events.project import EventProjector
from events.store import EventStore


OUT = ROOT / "tmp" / "smoke"
WT = "VDGV"
ALTERNATIVES = ("F", "E", "W", "I")
SEED = 20260912


def synthetic_landscape() -> pd.DataFrame:
    """Return a fixed complete 2^4 landscape with mild, known epistasis."""
    rows = []
    for residues in product(*((wt, alternative) for wt, alternative in zip(WT, ALTERNATIVES))):
        variant = "".join(residues)
        fitness = 1.0
        fitness += 1.5 if variant[0] == "F" else 0.0
        fitness += 0.2 if variant[1] == "E" else 0.0
        fitness += 0.8 if variant[2] == "W" else 0.0
        fitness += 0.5 if variant[3] == "I" else 0.0
        fitness += 0.4 if variant[0] == "F" and variant[2] == "W" else 0.0
        rows.append({"Variants": variant, "HD": sum(a != b for a, b in zip(variant, WT)),
                     "Fitness": round(fitness, 3)})
    return pd.DataFrame(rows)


def run() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    landscape = synthetic_landscape()
    csv_path = OUT / "synthetic_landscape.csv"
    events_path = OUT / "campaign.events.jsonl"
    projection_path = OUT / "campaign.events.sqlite"
    metrics_path = OUT / "campaign.metrics.json"
    figure_path = OUT / "campaign.png"
    readme_path = OUT / "README.md"
    for path in (events_path, projection_path):
        path.unlink(missing_ok=True)
    landscape.to_csv(csv_path, index=False)

    # The production pipeline is supplied only its observed pool.  In this complete
    # toy truth set, append candidate identities (without fitness) so its mutation
    # designer can apply the same measured-space guard as it does in the full run.
    original_pipeline = campaign.run_pipeline
    measured_space = [{"Variants": sequence} for sequence in landscape["Variants"]]

    def pipeline_with_synthetic_truth(pool, *args, **kwargs):
        return original_pipeline([*pool, *measured_space], *args, **kwargs)

    campaign.run_pipeline = pipeline_with_synthetic_truth
    try:
        store = EventStore(events_path)
        report = campaign.run_campaign(landscape, seed=SEED, n_rounds=2, budget=2,
                                       pool_size=8, event_store=store, use_llm=False)
        store.verify()
    finally:
        campaign.run_pipeline = original_pipeline

    report["smoke_notice"] = {
        "dataset": "SYNTHETIC SMALL-SCALE LANDSCAPE (not measured GB1 data)",
        "seed": SEED,
        "formal_result_comparable": False,
        "warning": "Do not compare these demonstration metrics with formal experiment results.",
    }
    metrics_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    campaign.plot_campaign(report, figure_path)
    event_count = EventProjector(events_path, projection_path).rebuild()
    readme_path.write_text(
        "# SYNTHETIC SMALL-SCALE SMOKE OUTPUT\n\n"
        "This directory was generated by `make smoke` from a fixed synthetic 16-variant "
        "landscape. It is not measured GB1 data; its metrics are not formal experimental results "
        "and must not be compared with report values.\n\n"
        f"- Fixed seed: `{SEED}`\n- Variants: `{len(landscape)}`\n"
        "- Workflow: data → Ridge predictor → five-role agent → four strategies\n"
        "- LLM: deterministic offline fallback (no API key used)\n",
        encoding="utf-8",
    )
    print("[smoke] SYNTHETIC SMALL-SCALE DATA — not comparable to formal results")
    print(f"[out] {csv_path.relative_to(ROOT)}")
    print(f"[out] {metrics_path.relative_to(ROOT)}")
    print(f"[out] {figure_path.relative_to(ROOT)}")
    print(f"[out] {events_path.relative_to(ROOT)} (verified hash chain)")
    print(f"[out] {projection_path.relative_to(ROOT)} ({event_count} projected events)")
    print(f"[out] {readme_path.relative_to(ROOT)}")


if __name__ == "__main__":
    run()
